#配置mysql数据库连接的属性
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm02?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver